In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits=load_digits()

In [2]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [3]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9638888888888889

In [4]:
svc=SVC(gamma='auto')
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.3611111111111111

In [5]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9777777777777777

K-fold cross validation
1.Basic Example

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


use KFold for our digits dataset

In [8]:
def getscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    score=model.score(x_test,y_test)
    return score

In [9]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [10]:
score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_l.append(getscore(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train,x_test,y_train,y_test))
    score_svm.append(getscore(SVC(gamma='auto'),x_train,x_test,y_train,y_test))
    score_rf.append(getscore(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

In [11]:
score_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [12]:
score_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [13]:
score_rf

[0.9265442404006677, 0.9465776293823038, 0.9232053422370617]

In [14]:
np.average(score_l)

0.9193099610461881

In [15]:
np.average(score_svm)

0.4346132442960489

In [16]:
np.average(score_rf)

0.9321090706733445

cross_val_score function

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
np.average(cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3))

0.9193099610461881

In [19]:
np.average(cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3))

0.4346132442960489

In [20]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3))

0.9321090706733445

parameter tuning for RandomForestClassifier  uaing KFold cross validation

In [21]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=10))

0.9454624456859093

In [22]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=10))

0.9426815642458101

In [23]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target,cv=10))

0.9515611421477341